=== chenjin19/firstproject/xml42/person.dtd
<!--子元素出现的位置必须一致， 默认出现一次, 
 	如果指定？ 表示出现 一次或0次
 	如果指定* 表示出现0次或n次
 	如果指定+ 表示 至少出现一次
 	#PCDATA表示子元素是字符元素-->
<!ELEMENT persons (person+)>
<!ELEMENT person (age,name,sex,tall,contact, partern+)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ELEMENT sex (#PCDATA)>
<!ELEMENT tall (#PCDATA)>
<!ELEMENT contact (telephone,mobile,qq)>
<!ELEMENT telephone (#PCDATA)>
<!ELEMENT mobile (#PCDATA)>
<!ELEMENT qq (#PCDATA)>
<!ELEMENT partern EMPTY>

<!--定义属性类型为ID时，属性值不能是数值类型-->
<!ATTLIST person id ID #REQUIRED>
<!ATTLIST partern pid ID #IMPLIED>
<!ATTLIST person copyright CDATA "@">

=== chenjin19/firstproject/xml42/src/main/resources/person01.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE persons SYSTEM "person.dtd">

<persons>
	<person id="A1001" copyright="op">
		<age>23</age>
		<name>张三</name>
		<sex>男</sex>
		<tall>1.75</tall>
		<contact>
			<telephone>8355998</telephone>
			<mobile>17773488663</mobile>
			<qq>4136707076</qq>
		</contact>
		<partern pid="B10001" />
	</person>
	
	<person id="A1002">
		<age>23</age>
		<name>张三</name>
		<sex>男</sex>
		<tall>1.75</tall>
		<contact>
			<telephone>8355998</telephone>
			<mobile>17773488663</mobile>
			<qq>4136707076</qq>
		</contact>
		<partern pid="B10002" />
	</person>
</persons>
